select 
	VEHICLE_CLASSES.DESCRIPTION as [Vehicle_Class],
  VEHICLE_JOB_PRICE_CLASSES.DESCRIPTION as [Job_Class],
	VEHICLE_TYPES.DESCRIPTION as [Vehicle_Type],
	VEHICLE_FAMILIES.FAMILY_NAME_CODE as [Vehicle_Family],
	BODY_STYLES.DESCRIPTION as [Body_Style],
	TRIM_LEVELS.TRIM_LEVEL_NAME as [Trim_Level]
FROM
	VIN_COMBO_05_06_07
		INNER JOIN VEHICLE_CLASSES ON (VIN_COMBO_05_06_07.VEHICLE_CLASS_ID = VEHICLE_CLASSES.CLASS_id)
    INNER JOIN VEHICLE_JOB_PRICE_CLASSES ON (VIN_COMBO_05_06_07.[Job_Price_Class_ID] = VEHICLE_JOB_PRICE_CLASSES.[Job_Price_ID])
		INNER JOIN VEHICLE_TYPES ON (VIN_COMBO_05_06_07.VEHICLE_TYPE_ID = VEHICLE_TYPES.TYPE_ID)
		INNER JOIN VEHICLE_FAMILIES ON (VIN_COMBO_05_06_07.FAMILY_ID = VEHICLE_FAMILIES.FAMILY_ID)
		INNER JOIN BODY_STYLES ON (VIN_COMBO_05_06_07.BODY_STYLE_ID = BODY_STYLES.BODY_STYLE_ID)
		INNER JOIN TRIM_LEVELS ON (VIN_COMBO_05_06_07.TRIM_LEVEL_ID = TRIM_LEVELS.TRIM_LEVEL_ID)
WHERE
	YEAR = 2012 AND
	VIN_CODES = 'R7V'
